---
- name: "App deployment using Ansible"
  hosts: default

  vars:
    ruby_build: ~/.rbenv/plugins/ruby-build/ruby-build
    rubyversion: 2.7.1

  
  tasks:
     - include_role:
          name: common
     - include_role:
          name: ruby
     - include_role:
          name: apache
     - include_role:
          name: passenger
     - include_role:
          name: nodejs
     - include_role:
           name: yarn
     - include_role:
           name: redis
